export type Language = 'zh' | 'en';
export type Params = Record<string, string | number>;
export type Translate = (message: string, params?: Params) => string;

// English messages are also the fallback for raw external diagnostics.
export const chinese: Record<string, string> = {
  'Dashboard navigation': '仪表盘导航', 'Usage overview': '用量总览', 'Task details': '任务明细',
  'Trends & methodology': '趋势与依据', 'Current account quota': '当前账号额度',
  '{percent} quota remaining': '额度剩余 {percent}', 'Next reset': '距离下次重置',
  'Current account quota and cross-account usage, clearly separated.': '当前账号额度与跨账号消耗，分开看清。',
  'Cross-account usage estimate': '跨账号用量估算', 'No project': '未分配项目',
  'May exceed 100%': '可超过 100%', 'API-equivalent estimate': 'API 等价估算',
  'Based on local records and observed quota changes.': '基于本地记录与观测到的额度变化估算。',
  'Estimation basis': '估算依据',
  'Across accounts': '跨账号', 'Local records': '本地记录',
  'Time zone: {zone}': '时区：{zone}', 'Starts': '开始', 'Ends / resets': '结束／重置',
  'Statistics start': '统计开始', 'Data through': '数据截至',
  'The current account’s quota window defines this range; equivalent usage combines local records across accounts.': '本范围按当前账号的额度重置周期划定；等效消耗汇总范围内跨账号的本地记录。',
  'This quota period has ended. Waiting for the renewed quota window.': '此额度周期已结束，正在等待新的额度周期。',
  'Showing the last confirmed account snapshot from {time}. Retrying automatically.': '显示 {time} 最后确认的账号数据，正在自动重试。',
  'Last confirmed account': '上次确认的账号',
  'Table view': '表格视图', 'Full table': '完整表格', 'Simple view': '精简视图',
  'Simple view shows one metric. Expand a task for all metrics, or select Full table to choose columns.': '精简视图显示一个指标。展开任务可查看全部指标，或切换完整表格设置显示列。',
  'Scroll horizontally for more columns, or choose Simple view.': '可左右滚动查看其余列，或切换精简视图。',
  'Quota %': '额度占比', 'Est. cost': '估算费用', '{plan} equiv.': '{plan} 等效消耗', 'Tokens': 'Token 数',
  'Account · Period': '账号 · 本周期', 'This period': '本周期', 'Lifetime': '任务累计', '7 days': '近 7 天',
  'Using previous calibration; updating in the background ({count}/5 percentage points).': '沿用历史校准值，后台持续校准（有效样本 {count}/5 个百分点）。',
  'Calibration reference updated': '校准参考值更新时间',
  'CLI account · Details': 'CLI 账号 · 详情',
  'More actions': '更多操作', 'Shown metric': '显示指标',
  'Scope help': '范围说明', 'Comparison help': '折算说明',
  'Equivalent usage · Cost · Tokens': '影响：等效消耗 · 费用 · Token',
  'Waiting for calibration': '等待校准', 'No priced usage in this range': '此范围暂无可估算用量',
  'Includes hidden tasks · + partial data · -- unavailable': '包含隐藏任务 · + 部分数据 · -- 暂不可用',
  'Usage account': '用量所属账号', 'Unknown account': '账号未知', 'API key account': 'API Key 账号',
  'Source: Monitor’s Codex CLI login. This may differ from the account in the Codex desktop app.': '来源：Monitor 使用的 Codex CLI 登录账号，可能与 Codex 桌面应用中的账号不同。',
  'Updated at {time}': '更新时间：{time}',
  'Account changed while reading usage. Waiting for the next refresh.': '读取用量时账号发生变化，等待下次刷新。',
  'Statistics time range': '统计时间范围',
  'Equivalent usage comparison': '等效消耗对比套餐',
  'All accounts': '跨账号',
  '{plan} equivalent usage': '{plan} 等效消耗',
  'One {plan} week = 100%': '一份 {plan} 周额度 = 100%',
  'Applies to equivalent usage, estimated cost, tokens, summaries and trends. Account quota attribution is only available for the current quota period.': '影响等效消耗、估算费用、Token 列，以及汇总和趋势；账号额度占比仅在本周期可用。',
  'Changes only equivalent usage: task and project rows, summary and trend. One {plan} weekly allowance = 100%.': '仅切换任务、项目、汇总和趋势中的等效消耗；一份 {plan} 周额度 = 100%。',
  'Equivalent usage compares all locally recorded accounts with one {plan} weekly allowance in the selected period. Values may exceed 100%.': '等效消耗将所选范围内本机各账号的用量，折算为一份 {plan} 周额度的百分比，可超过 100%。',
  'Nominal comparison: Pro 20x : Pro 5x : Plus = 20 : 5 : 1. The same usage is multiplied by 1, 4 or 20 from the calibrated 20x estimate. This does not change the recorded account tier or represent an official bill.': '按标称倍率估算：Pro 20x : Pro 5x : Plus = 20 : 5 : 1。同一用量在原 20x 校准估算上分别乘以 1、4、20；不会修改记录中的账号套餐，也不代表官方账单。',
  'Current quota period': '本周期', 'Last 7 days': '近 7 天', 'Time range': '统计时间范围',
  'Current account · This period': '当前账号 · 本周期', 'All accounts · Selected period': '跨账号 · 所选范围',
  'Selected period': '所选时间范围', 'Selected period · USD': '所选范围 · 美元',
  'Estimated cost': '估算费用', 'One 20x week = 100%': '一份 20x 周额度 = 100%',
  'Scope totals': '范围合计', '{count} tasks': '{count} 个任务',
  'Includes hidden tasks in the selected archive scope. Search and row filters only change the list. + means partial data; -- means unavailable.': '包含当前归档范围内被隐藏的任务。搜索和行筛选仅影响列表。+ 表示部分数据，-- 表示不可用。',
  'Daily trend and project ranking': '每日趋势与项目排行', 'Metric': '统计指标', 'Daily usage': '每日用量', 'Top 5 projects': '项目消耗前 5 名',
  'No daily usage records in this period.': '此时间范围内没有每日用量记录。',
  'The trend shows dates with recorded usage in the selected period. Rankings use the full selected scope, including hidden rows.': '趋势显示所选范围内有用量记录的日期。排行汇总整个统计范围，包含被隐藏的行。',
  'Account attribution is available only for the current quota period.': '账号额度分配仅在本周期范围可用。',
  'Refreshing…': '正在刷新…', 'Automatic refresh paused': '自动刷新已暂停', 'Next refresh in {time}': '{time} 后刷新', 'Refresh now': '立即刷新',
  'Rebuild statistics': '重新统计',
  'Re-read logs in the current archive scope. Saved quota attribution is preserved.': '重新读取当前归档范围内的日志，保留已保存的额度分配。',
  'View options': '视图选项', 'Density': '显示密度', 'Comfortable': '舒适', 'Compact': '紧凑', 'Visible columns': '显示列',
  'Loading the selected period. Previous results remain labeled with their original period.': '正在加载所选时间范围，完成前保留原范围的结果和标识。',
  'All available history': '全部可用历史', 'Period unavailable': '周期暂不可用',
  'Statistics help and estimation basis': '统计说明与估算依据',
  '20x equivalents use one Pro 20x weekly allowance as 100%, for usage in the selected period. All locally recorded accounts are included; values may exceed 100%.': '20x 等效消耗以一份 Pro 20x 周额度为 100%，折算所选时间范围内本机各账号的用量，数值可以超过 100%。',
  'Calibration observations': '校准样本', '{count} percentage points': '{count} 个百分点',
  'Estimated cost per 1% of 20x': '20x 每 1% 对应估算费用', 'Unpriced tokens': '未定价 Token', 'Tokens without timestamps': '缺少时间戳的 Token',
  'Daily boundary time zone': '每日统计时区', 'Last successful refresh': '上次成功刷新', 'Scrollable task table': '可滚动任务表格',
  'Today and Last 7 days use calendar days on the monitor computer. Current quota period follows the account reset window. Account quota attribution is only available for that period; no historical account totals are fabricated.': '今天和近 7 天按监控电脑的自然日统计，近 7 天包含今天；本周期按账号额度重置时间计算。账号额度分配仅有本周期数据，其他时间范围显示不可用。',
  'Project and scope totals include hidden rows. Click column headings to sort. + means incomplete data; -- means unavailable.': '项目和范围合计包含被隐藏的行。点击列标题可排序。+ 表示数据不完整，-- 表示不可用。',
  'API-equivalent cost for recorded usage in the selected period. This is an estimate, not a ChatGPT subscription charge, and excludes tool-call fees.': '所选时间范围内已记录用量的 API 等价估算费用，并非 ChatGPT 套餐账单，不包含工具调用费用。',
  'Auto-updating': '自动刷新',
  'Task refresh interval': '任务自动刷新间隔',
  '30 seconds': '30 秒',
  '1 minute': '1 分钟',
  '{count} minutes': '{count} 分钟',
  '20x equivalent usage': '20x 等效消耗',
  'All accounts · Weekly estimate': '跨账号 · 本周估算',
  '20x equivalent: one 20x weekly allowance = 100%; all accounts recorded locally are combined, with no 100% cap. Uses the current weekly period and selected archive scope.': '20x 等效消耗：一份 20x 周额度为 100%，合计本机记录中的各账号消耗，不设 100% 上限。采用当前周周期和选定的归档范围。',
  'All recorded Pro accounts are treated as 20x, as confirmed by the owner. The conversion uses observed weekly quota changes and API-equivalent token costs; it is not an official allowance or bill. Missing logs, other devices, tools and unpriced models can affect the estimate.': '根据用户确认，记录中的 Pro 账号均按 20x 处理。使用观测到的周额度变化和 Token 的 API 等价费用校准，不代表官方额度或账单。缺失日志、其他设备、工具和未定价模型可能影响估算。',
  'Period: {start} – {end}.': '统计周期：{start} 至 {end}。',
  'Waiting for enough recorded 20x weekly quota changes; -- means unavailable.': '等待足够的 20x 周额度变化记录完成校准；-- 表示暂不可用。',
  'Estimated 20x weekly equivalents for all local accounts in this project. Includes hidden rows in the selected scope. + means some usage is missing.': '此项目各账号本地记录的 20x 周额度等效估算，包含当前范围内被隐藏的行。+ 表示部分用量缺失。',
  'Estimated local usage across accounts in the current weekly period, divided by the calibrated cost of 1% of a 20x allowance. May exceed 100%. + means unpriced usage is excluded; -- means unavailable.': '当前周周期各账号的本地用量，除以校准得到的 20x 每 1% 额度对应费用。可以超过 100%。+ 表示未计入没有模型价格的用量；-- 表示暂不可用。',
  'Tasks': '任务', 'Task': '任务', 'Status': '状态', 'Activity': '最近活动',
  'Active': '进行中', 'Today': '今天', 'All': '全部', 'Finished': '已结束', 'Archived': '已归档',
  'Search tasks': '搜索任务', 'Search tasks or projects…': '搜索任务或项目…',
  'Filter tasks': '筛选任务', 'Sort tasks': '任务排序', 'Highest usage': '用量从高到低', 'Last activity': '最近活动',
  'Ascending': '升序', 'Descending': '降序', '{column} · {direction}': '{column} · {direction}',
  'Sort {column}: {direction}': '按{column}排序：{direction}',
  'Click a column heading to reverse its sort. Projects use their full totals or latest activity; tasks sort within each project. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题切换升降序。项目按全部任务的汇总值或最近活动排序，任务在各自项目内排序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Hide archived tasks': '隐藏归档任务', 'Show archived tasks': '显示归档任务',
  'Group by project': '按项目分组',
  'Project totals include quota, lifetime cost and lifetime tokens for unarchived tasks and the selected archives. Search and hiding rows do not change totals. + means incomplete data; -- means unavailable. The account quota covers all activity.': '项目汇总未归档任务和选定归档的额度占比、累计费用及总 Token 数，搜索或隐藏行不改变汇总。+ 表示数据不完整，-- 表示不可用。账户总额度覆盖全部活动。',
  'Click a column heading to sort all tasks in the selected scope, then click again to reverse. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题对当前范围内的全部任务排序，再次点击切换升降序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Estimated lifetime API-equivalent cost of tasks in this project within the selected scope. + means a partial estimate; -- means unavailable.': '当前统计范围内此项目全部任务的累计 API 等价估算费用。+ 表示部分估算，-- 表示不可用。',
  'Recorded lifetime tokens in this project: {count}. + means incomplete data.': '此项目记录的累计 Token 总数：{count}。+ 表示数据不完整。',
  'Calculate all archives': '统计所有归档',
  'Only calculate the latest 30 archives': '仅统计最近 30 个归档',
  'Return to the latest 30 archives': '返回最近 30 个归档',
  'Retry all archive statistics': '重试统计所有归档',
  'Calculating all archives…': '正在统计全部归档…',
  'Calculating all archives… Keeping the previous results until complete.': '正在统计全部归档…完成前保留原有结果。',
  'Statistics include all {count} archived tasks.': '当前统计全部 {count} 个归档任务。',
  'Statistics include only the {count} most recently archived tasks.': '当前仅统计最近 {count} 个归档任务。',
  'Only hide archived rows; the selected archive scope still counts toward usage.': '只隐藏归档任务行，当前选定范围内的归档仍计入统计。',
  'Project percentages sum unarchived tasks and the selected archives; search and hiding rows do not change those totals. + means some usage is unknown. The account quota still covers all activity.': '项目占比汇总未归档任务和当前选定的归档；搜索或隐藏行不改变汇总。+ 表示部分用量未知。账户总额度仍覆盖全部活动。',
  'Click a column heading to reverse its sort. Projects use totals in the selected scope or latest activity; tasks sort within each project. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题切换升降序。项目按当前统计范围的汇总值或最近活动排序，任务在各自项目内排序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Project total for this period within the selected archive scope, including hidden rows. + means additional usage is unknown.': '当前归档统计范围内的项目本周期额度占比，包含被隐藏的行。+ 表示还有未知用量。',
  'Includes selected archives': '含选定范围的归档',
  'Only hide archived rows; all archives still count toward usage.': '只隐藏列表中的归档任务，用量统计仍包含全部归档任务。',
  'Show more archived tasks ({count} remaining)': '显示更多归档任务（还有 {count} 个）',
  'Displayed / matching tasks': '当前显示 / 匹配任务总数',
  '{shown} shown / {total} total tasks': '{shown} 显示 / {total} 总任务',
  'Last successful refresh: {time}': '上次成功刷新：{time}',
  'Update failed · showing last data': '刷新失败 · 显示上次数据',
  'Auto-updating · every 30 s': '自动刷新 · 每 30 秒', 'Loading task usage…': '正在加载任务用量…',
  'Could not refresh tasks: {error}': '无法刷新任务：{error}', 'Loading tasks…': '正在加载任务…', 'No matching tasks.': '没有匹配的任务。',
  'Consumption before observation and increments without sufficient recorded usage remain unattributed. Filters do not change attribution.': '开始观测前的消耗，以及缺少足够用量记录的增量，保留为未分配额度。筛选不会改变分配结果。',
  'Attribution observed since {time} · Unattributed quota: {percent}': '额度分配观测始于 {time} · 未分配额度：{percent}',
  'Project percentages sum all tasks in this period, regardless of filters; + means some task usage is unknown.': '项目百分比汇总全部任务的本周期额度占用，不受列表筛选影响；+ 表示部分任务用量未知。',
  'Project total for this period, including hidden archives. + means additional usage is unknown.': '该项目全部任务的本周期额度占用之和，包含未显示的归档任务。+ 表示已有统计之外仍有未知用量。',
  'Includes all archives': '含全部归档任务', 'Some usage unknown': '部分用量未知',
  'Unassigned project': '未分配项目', 'Unknown project · {id}': '未识别项目 · {id}',
  'Approx. quota %': '估算额度占比', 'Observed this period': '本周期观测值',
  'Estimated total cost': '估算总费用', 'Task lifetime · USD': '任务累计 · 美元',
  'Total tokens': '总 Token 数', 'Task lifetime': '任务累计', 'Archived at {time}': '归档于 {time}',
  'Open in Codex ↗': '在 Codex 中打开 ↗', 'View live transcript and run': '查看实时记录和运行详情',
  'Task preview': '任务预览', 'No transcript preview available.': '暂无对话预览。',
  'Path': '路径', 'Source': '来源', 'Runs': '运行次数', 'Unavailable': '不可用',
  '{count} total': '总计 {count}', '{count} input': '输入 {count}', '{count} cached': '缓存读取 {count}',
  '{count} cache writes': '缓存写入 {count}', '{count} output': '输出 {count}', '{count} reasoning': '推理 {count}',
  'No API-equivalent cost can be estimated because the recorded model has no matching standard API price. This is not a billed ChatGPT or Codex charge.': '记录中的模型没有匹配的标准 API 价格，无法估算 API 等价费用。这不是 ChatGPT 或 Codex 的实际账单费用。',
  'Lower-bound API-equivalent estimate for recorded usage whose model has a standard API token price. The + indicates that usage from unpriced internal or unknown models is excluded. This is not a billed ChatGPT or Codex charge and excludes tool-call fees.': '这是已知模型价格对应的 API 等价费用下限。+ 表示未计入内部模型或未知模型的用量。这不是 ChatGPT 或 Codex 的实际账单费用，也不包含工具调用费用。',
  'Estimated API-equivalent cost for all recorded token usage in this task, using the recorded model and standard API token prices. It is not a billed ChatGPT or Codex charge and excludes tool-call fees.': '按记录的模型和标准 API Token 价格估算此任务的累计 API 等价费用。这不是 ChatGPT 或 Codex 的实际账单费用，也不包含工具调用费用。',
  'Approximate per-task usage is unavailable because Codex did not expose the current primary quota limit and reset period.': 'Codex 未提供当前主要额度上限和重置周期，暂时无法估算单个任务的额度占比。',
  'Overall Codex': 'Codex 总体', 'API-equivalent cost of priced usage': '已有模型价格的用量对应的 API 等价费用',
  'available local activity': '可用的本地活动记录',
  'Estimated share of {limit} {window} quota attributed to this task during observation. Each quota increase is allocated using {basis}, then accumulated. Earlier allocations are preserved. Pre-observation consumption and increments with missing or unpriced usage remain unattributed. -- means no allocation yet or unavailable data, not zero consumption. This is an estimate, not an official OpenAI per-task measurement. Resets at {time}.': '观测期间分配给此任务的 {limit} {window} 额度估算占比。每次额度增量按{basis}分配后累加，保留之前的分配。开始观测前的消耗，以及缺少用量或价格记录的增量，保留为未分配额度。-- 表示尚未分配或数据不可用，不表示零消耗。这是估算值，不是 OpenAI 官方单任务测量值。重置时间：{time}。',
  'Unknown': '未知', 'Now': '刚刚', '{count} min ago': '{count} 分钟前', '{count} hr ago': '{count} 小时前', '{count} d ago': '{count} 天前',
  'Untitled task · {id}': '未命名任务 · {id}',
  'Overall Codex usage': 'Codex 总体用量', 'remaining': '剩余', 'Quota used': '已用额度', 'Time elapsed': '已过时间',
  'Pace unavailable': '暂无法比较消耗进度', 'Usage is ahead of elapsed time': '额度消耗快于时间进度',
  'Usage is below the proportional pace': '额度消耗慢于时间进度', 'Usage is in line with elapsed time': '额度消耗与时间进度基本一致',
  'Loading overall Codex usage…': '正在加载 Codex 总体用量…', 'Overall Codex quota is unavailable.': 'Codex 总体额度暂不可用。',
  'Waiting for the renewed quota': '等待更新后的额度', '{percent} quota used': '已用额度 {percent}', '{percent} of period elapsed': '本周期已过 {percent}',
  'Codex has not reported the new period yet.': 'Codex 尚未报告新周期的数据。', 'The period or usage data is incomplete.': '周期或用量数据不完整。',
  'Consumption follows the proportional pace of the period.': '额度消耗与本周期的时间进度基本一致。',
  '{count} percentage points above the proportional pace.': '额度消耗比时间进度高 {count} 个百分点。',
  '{count} percentage points below the proportional pace.': '额度消耗比时间进度低 {count} 个百分点。',
  'Reset time unavailable': '重置时间不可用', 'Resets in {duration}': '{duration} 后重置',
  '{days}d {hours}h': '{days} 天 {hours} 小时', '{hours}h {minutes}m': '{hours} 小时 {minutes} 分钟', '{minutes}m': '{minutes} 分钟',
  'Auto shutdown': '自动关机', 'Dry-run': '模拟运行', 'On': '开启', 'Off': '关闭', 'Power': '电源', 'Idle shutdown': '空闲后关机',
  'Enable': '启用', 'Disable': '停用', 'Shutdown in {duration}': '{duration} 后关机',
  'Codex app-server initialized': 'Codex 服务已初始化', 'Waiting for Codex app-server': '正在等待 Codex 服务',
  'Connected': '已连接', 'Connection: {status}': '连接状态：{status}',
  'API-equivalent cost, not a plan charge · Codex Spark excluded': 'API 等价估算费用，并非套餐账单 · 不含 Codex Spark',
  'Off. Enable it to shut down after Codex work finishes.': '已关闭。启用后将在 Codex 任务结束后关机。',
  'Dry-run mode is on. Countdown will not shut down this computer.': '模拟运行模式已开启，倒计时不会让这台电脑真正关机。',
  'Windows shutdown is scheduled. New Codex activity will cancel it.': '已安排 Windows 关机。新的 Codex 活动会取消关机。',
  'No active sessions. Scheduling Windows shutdown after {seconds}s idle.': '没有进行中的任务。空闲 {seconds} 秒后安排 Windows 关机。',
  'Waiting for {count} active Codex sessions to finish.': '正在等待 {count} 个进行中的 Codex 任务结束。',
  'Waiting for one active Codex session to finish.': '正在等待 1 个进行中的 Codex 任务结束。',
  'Armed. Shutdown starts after {idle}s idle, then Windows waits {delay}s.': '已就绪。空闲 {idle} 秒后启动关机计时，Windows 再等待 {delay} 秒。',
  'Shutdown {status}': '关机：{status}', 'No shutdown scheduled': '未安排关机', 'Windows timer {duration}': 'Windows 关机倒计时 {duration}', 'Schedules in {duration}': '{duration} 后安排关机',
  'Run detail': '运行详情', 'Waiting for this run to appear.': '正在等待此运行的数据。',
  'If you opened a stale URL, go back to the dashboard.': '如果打开的是已失效的链接，请返回仪表盘。', 'Back to dashboard': '返回仪表盘',
  'waiting on you': '等待你处理', 'autonomous': '自主执行', 'automation {status}': '自动化：{status}',
  'Tracked threads': '跟踪的任务数', 'Root thread': '根任务', 'Shutdown': '关机', 'not scheduled': '未安排',
  'Arm shutdown rule': '启用关机规则', 'Cancel shutdown': '取消关机',
  'Thread tree': '任务树', 'Root plus spawned agents': '根任务与派生智能体', 'Waiting for thread data…': '正在等待任务数据…',
  'No recent preview yet.': '暂无最近活动预览。', 'Transcript': '对话记录', 'Select a thread': '选择任务',
  'Pick a thread to inspect its stream.': '选择一个任务以查看实时记录。', 'Tool: {name}': '工具：{name}',
  'Inspector': '检查面板', 'No thread selected': '未选择任务', 'Thread metadata appears here.': '任务信息将显示在这里。',
  'Latest turn': '最近一轮', 'no turn yet': '暂无轮次', 'No recent activity summary.': '暂无最近活动摘要。',
  'Plan': '计划', 'No plan updates captured for this turn.': '本轮尚未记录到计划更新。',
  'Diff': '变更差异', 'No diff emitted yet.': '暂无变更差异。', 'Commands': '命令', 'No command output in this turn yet.': '本轮暂无命令输出。',
  'Pending requests': '待处理请求', 'No pending human requests for this thread.': '此任务没有等待人工处理的请求。', 'Shutdown timer': '关机计时器',
  'Waiting on command approval': '等待命令审批', 'Waiting on file-change approval': '等待文件修改审批',
  'Waiting on extra permissions': '等待额外权限', 'Waiting on user input': '等待用户输入', 'Waiting on MCP elicitation': '等待 MCP 信息补充', 'Waiting on external request': '等待外部请求',
  'Command approval': '命令审批', 'File-change approval': '文件修改审批', 'Extra permissions': '额外权限', 'User input': '用户输入', 'MCP elicitation': 'MCP 信息补充', 'External request': '外部请求',
  'Technical details': '技术详情', 'Unable to load data.': '无法加载数据。', 'Action failed.': '操作失败。',
  'Failed to fetch': '网络请求失败', 'NetworkError when attempting to fetch resource.': '网络请求失败',
  'History pagination did not advance.': '任务列表分页没有前进，请稍后刷新。', 'Forbidden origin': '此访问来源未获允许',
  'Codex did not return rate limit data.': 'Codex 未返回额度限制数据。', 'Codex sent malformed rate limit data.': 'Codex 返回的额度数据格式无效。',
  'Request failed with {status}': '请求失败，状态码 {status}',
  'Weekly': '每周', '5-hour': '5 小时', 'Daily': '每日', '{minutes}-minute': '{minutes} 分钟', '{hours}-hour': '{hours} 小时', '{days}-day': '{days} 天',
  'Running': '运行中', 'Idle': '空闲', 'Error': '错误', 'Waiting for you': '等待处理', 'Not loaded': '未加载',
  'Settled': '已结束', 'Disabled': '已停用', 'Armed': '已就绪', 'Debouncing': '等待空闲稳定', 'Scheduled': '已安排',
  'Completed': '已完成', 'Failed': '失败', 'Interrupted': '已中断', 'In progress': '进行中', 'Pending': '待处理',
  'Connecting': '连接中', 'Retrying': '重试中', 'Reconnecting': '重新连接中',
  'CLI': '命令行', 'VS Code': 'VS Code', 'Execution': '执行', 'App server': '应用服务', 'Subagent': '子智能体',
  'Review subagent': '审查子智能体', 'Compaction subagent': '压缩子智能体', 'Spawned subagent': '派生子智能体', 'Other subagent': '其他子智能体',
  'User message': '用户消息', 'Assistant message': '助手消息', 'Reasoning': '推理', 'Command': '命令', 'File change': '文件修改', 'Web search': '网页搜索', 'Image': '图片', 'Tool call': '工具调用',
  'Agent message': '智能体消息', 'Command execution': '命令执行', 'Agent collaboration': '智能体协作', 'MCP tool call': 'MCP 工具调用',
  'Window': '周期', 'Context compaction': '上下文压缩', 'Image generation': '图片生成', 'Entered review mode': '进入审查模式', 'Exited review mode': '退出审查模式',
  'Codex app-server is not running.': 'Codex 服务未运行。',
};

export function translate(language: Language, message: string, params: Params = {}): string {
  const template = language === 'zh' && Object.hasOwn(chinese, message) ? chinese[message] : message;
  return template.replace(/\{(\w+)\}/g, (token, key: string) => Object.hasOwn(params, key) ? String(params[key]) : token);
}

const labels: Record<string, string> = {
  running: 'Running', idle: 'Idle', error: 'Error', waiting_on_human: 'Waiting for you', not_loaded: 'Not loaded',
  settled: 'Settled', disabled: 'Disabled', armed: 'Armed', debouncing: 'Debouncing', scheduled: 'Scheduled', 'dry-run': 'Dry-run',
  completed: 'Completed', failed: 'Failed', interrupted: 'Interrupted', inProgress: 'In progress', pending: 'Pending',
  live: 'Connected', connecting: 'Connecting', retrying: 'Retrying', reconnecting: 'Reconnecting',
  cli: 'CLI', vscode: 'VS Code', exec: 'Execution', appServer: 'App server', unknown: 'Unknown', subAgent: 'Subagent',
  subAgentReview: 'Review subagent', subAgentCompact: 'Compaction subagent', subAgentThreadSpawn: 'Spawned subagent', subAgentOther: 'Other subagent',
  commandApproval: 'Command approval', fileChangeApproval: 'File-change approval', permissionsApproval: 'Extra permissions',
  toolUserInput: 'User input', mcpElicitation: 'MCP elicitation', dynamicToolCall: 'Tool call', authRefresh: 'External request',
  reasoning: 'Reasoning', plan: 'Plan', imageView: 'Image', contextCompaction: 'Context compaction',
  imageGeneration: 'Image generation', enteredReviewMode: 'Entered review mode', exitedReviewMode: 'Exited review mode'
};

export function createI18n(language: Language) {
  const locale = language === 'zh' ? 'zh-CN' : 'en-US';
  const t: Translate = (message, params) => translate(language, message, params);
  return {
    language, locale, t,
    label: (value: string) => t(Object.hasOwn(labels, value) ? labels[value] : value),
    dateTime: (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString(locale) : t('Unavailable'),
    time: (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleTimeString(locale) : t('Unavailable'),
    windowLabel: (value: string) => {
      if (Object.hasOwn(chinese, value)) return t(value);
      const match = value.match(/^(\d+)-(minute|hour|day)$/i);
      return match ? t(`{${match[2].toLowerCase()}s}-${match[2].toLowerCase()}`, { [`${match[2].toLowerCase()}s`]: match[1] }) : value;
    },
    error: (value: string) => {
      const status = value.match(/^Request failed with (\d+)$/);
      return status ? t('Request failed with {status}', { status: status[1] }) : t(value);
    }
  };
}
export type I18n = ReturnType<typeof createI18n>;
export const LANGUAGE_STORAGE_KEY = 'codex-monitor-language';
export function initialLanguage(storage?: Pick<Storage, 'getItem'>): Language {
  try { return storage?.getItem(LANGUAGE_STORAGE_KEY) === 'zh' ? 'zh' : 'en'; }
  catch { return 'en'; }
}
