export type Language = 'zh' | 'en';
export type Params = Record<string, string | number>;
export type Translate = (message: string, params?: Params) => string;

// English messages are also the fallback for raw external diagnostics.
export const chinese: Record<string, string> = {
  'Model comparison': '模型用量对比',
  'Time zone': '时区',
  'Unknown model': '未知模型',
  'API-equivalent cost': 'API 等价费用',
  'Sort by {column}': '按{column}排序',
  'Models in the selected period': '所选时间范围内的模型用量',
  'Models are taken from each recorded usage event. Task counts can overlap across models.': '按每次用量事件记录的模型统计；同一任务可能使用多个模型，任务数不可直接相加。',
  'Input includes cached input. Output includes reasoning output. + marks partial totals; -- means unavailable, not zero.': '输入包含缓存输入，输出包含推理输出。+ 表示部分总量；-- 表示不可用，不是零。',
  'Historical cache efficiency': '历史缓存效率',
  'Recorded cache hit': '已记录缓存命中率',
  'Uncached input': '未缓存输入',
  'Total input': '总输入',
  'Cache hit = total cached input / total input in this period; it is not an average of model percentages. Missing records may change this rate.': '缓存命中率 = 本范围缓存输入总量 / 输入总量，并非各模型百分比的平均值；缺失记录可能影响比率。',
  'No model usage records in this period.': '此时间范围内没有模型用量记录。',
  'Model usage is unavailable. -- does not mean zero usage.': '模型用量暂不可用。-- 不表示零消耗。',
  'Model price basis': '模型价格依据',
  'API-equivalent token estimates use the stored rate catalog; they are not subscription charges or official quota deductions. Tool-call fees are excluded.': '按本地保存的单价表估算 API 等价费用，并非订阅账单或官方额度扣减；不含工具调用费用。',
  'USD per 1 million tokens': '美元 / 每百万 Token',
  'Latest recorded price check': '最近有记录的价格核对',
  'Recorded price check': '价格核对记录',
  'Not recorded': '无记录',
  'Official pricing reference': '官方价格参考',
  'Rates used for estimates': '估算采用的单价',
  'Priced share of recorded tokens': '已记录 Token 的定价覆盖率',
  'Priced recorded tokens': '已定价 Token',
  'Unpriced recorded tokens': '未定价 Token',
  'Price coverage is weighted by recorded total tokens. Missing records may change this percentage.': '定价覆盖率按已记录的总 Token 加权计算；缺失记录可能影响比例。',
  'Unpriced models': '未定价模型',
  'Cache write input': '缓存写入输入',
  'The stored long-context calculation assumes {input}× input and {output}× output rates above {tokens} input tokens; these multipliers are not verified universal official rates.': '现有长上下文计算假设：超过 {tokens} 输入 Token 时，输入按 {input} 倍、输出按 {output} 倍单价计算；这些倍数未经核实为普遍适用的官方单价。',
  'API-equivalent estimates, not ChatGPT plan charges. Existing pricing table retained: GPT-6 input, cached-input and output rates have a recorded verification date of 2026-09-26; other model rates are carried over without a recorded check date. Cache-write rates (1.25x input) and high-context multipliers across models are inherited calculation assumptions, not verified universal official rates. Unknown models remain unpriced. High-context multipliers apply when an event input exceeds the threshold; cache-write tokens are charged separately and reasoning tokens are included in output.': '这是 API 等价估算，并非 ChatGPT 套餐账单。沿用现有价格表：GPT-6 输入、缓存输入及输出单价有 2026-09-26 的核对记录；其他模型沿用旧值，没有核对日期记录。缓存写入单价（输入的 1.25 倍）及各模型的长上下文倍数是既有计算假设，未经核实为普遍适用的官方单价。未知模型保留为未定价。单次事件的输入超过阈值时启用长上下文倍数；缓存写入另计，推理 Token 已包含在输出中。',
  'Price basis is unavailable.': '价格依据暂不可用。',
  'Models without a matching price remain unpriced; priced usage is shown as a partial estimate when other usage is missing.': '无匹配价格的模型保留为未定价；存在其他缺失用量时，已定价用量显示为部分估算。',
  'Daily cache hit uses cached input / total input. Missing records may change the rate; no input is shown as --.': '每日缓存命中率按缓存输入 / 总输入计算；缺失记录可能影响比率，无输入时显示 --。',
  'Bars are stacked by the recorded model. Select a day to see its model usage and tasks below.': '柱形按记录中的模型堆叠；选择日期可在下方查看当天的模型用量和任务。',
  'Model breakdown is unavailable for some days; their recorded totals are still shown.': '部分日期缺少模型明细，仍显示这些日期已记录的总量。',
  'Model legend': '模型图例',
  'Usage on {date}': '{date} 当日用量',
  'Models on {date}': '{date} 当日模型用量',
  'Tasks on {date}': '{date} 当日任务',
  'Model breakdown is unavailable for this day.': '这一天的模型明细暂不可用。',
  'These values include only this day’s recorded usage. Open a task to inspect its details.': '下列数值仅含当天记录的用量，打开任务可查看详情。',
  'Daily task details are unavailable for some records.': '部分记录缺少每日任务明细。',
  'No task usage records for this day.': '这一天没有任务用量记录。',
  'Daily usage is unavailable. -- does not mean zero usage.': '每日用量暂不可用。-- 不表示零消耗。',
  'Export report': '导出报告',
  'Exports the selected range across accounts, including hidden rows and the selected archive scope.': '导出所选时间范围的跨账号统计，包含隐藏行及选定归档范围。',
  'Include task and project display names': '包含任务和项目显示名称',
  'Names are replaced with aliases by default. Prompts, paths and account identity are always omitted.': '默认以别名替换名称；始终省略提示词、路径和账号身份。',
  'Download HTML': '下载 HTML',
  'Download CSV': '下载 CSV',
  'Download JSON': '下载 JSON',
  'Report export failed.': '报告导出失败。',
  'Report downloaded.': '报告已下载。',
  'Download started.': '下载已开始。',
  'Task request timed out. Previous results are kept; retry refresh.': '任务请求超时，已保留之前的结果，可以重新刷新。',
  'Could not scan local task statistics; the previous snapshot remains unchanged.': '暂时无法扫描本地任务，已保留上次统计结果。',
  'Could not read local task statistics; the previous snapshot remains unchanged.': '暂时无法读取本地任务，已保留上次统计结果。',
  'Account quota, recent token reports and historical usage.': '账号额度、近期 Token 消耗与历史汇总。',
  'Bars compare tasks within this list.': '横条仅比较本榜任务。',
  'Live token reports': '实时 Token',
  'Live token time window': '实时 Token 时间窗口',
  '1 s': '1 秒',
  'Per-second average over the last minute': '最近 1 分钟的每秒平均用量',
  'Per-second average · Last minute ÷ 60': '每秒均值 · 最近 1 分钟 ÷ 60',
  'Input (tok/s)': '输入（Token/秒）',
  'Output (tok/s)': '输出（Token/秒）',
  'Tasks reporting in the last minute': '最近 1 分钟内有上报的任务',
  'Per-second input and output are the last minute totals divided by 60, not measurements sampled every second. Cache hit and task count use the same minute.': '每秒输入和输出为最近 1 分钟总量除以 60，并非逐秒采集；缓存命中率和任务数仍按该分钟统计。',
  'Last 1 minute': '最近 1 分钟',
  'Last 5 minutes': '最近 5 分钟',
  'Last 20 minutes': '最近 20 分钟',
  'Last 1 hour': '最近 1 小时',
  '1 min': '1 分钟',
  '5 min': '5 分钟',
  '20 min': '20 分钟',
  '1 hour': '1 小时',
  'Local chats · Across accounts': '本机对话 · 跨账号',
  'Local chats · Across accounts · Independent of account and date filters': '本机对话 · 跨账号 · 不受账号和日期筛选影响',
  'Includes cached input': '包含缓存输入',
  'Includes reasoning output': '包含推理输出',
  'Cache hit': '缓存命中率',
  'Cached input / input': '缓存输入 / 总输入',
  'Reporting tasks': '有记录任务',
  'Tasks with reports in this window': '本窗口内有上报的任务',
  'Last report': '最近上报',
  'Snapshot at': '快照时间',
  'Updated at': '更新时间',
  'Collecting reports': '正在收集上报',
  'Collecting since {time}': '自 {time} 开始收集',
  'Window still filling': '窗口尚未收集完整',
  'No reports in this window': '本窗口内没有上报',
  'Recent reports': '近期上报',
  'Stale snapshot': '快照已过期',
  'Current window unavailable. Showing the last received snapshot.': '当前窗口数据不可用，显示上次收到的快照。',
  'Local token reports are unavailable. -- does not mean zero usage.': '本机 Token 上报暂不可用。-- 不表示零消耗。',
  'About these numbers': '说明',
  'Memory only · 1 hour': '仅内存保留 1 小时',
  'Windows count token reports when Monitor receives them, not when tokens are generated.': '按 Monitor 收到 Token 上报的时间计入窗口，并非 Token 实际生成时间。',
  'These statistics stay in memory for a rolling hour and clear when Monitor restarts. No history is saved.': '仅在内存中保留滚动 1 小时统计，Monitor 重启后清空，不保存历史。',
  'Independent of account and date filters. Reports cannot be attributed to the current login. New tasks may take up to one minute to appear.': '不受账号和日期筛选影响，无法归属到当前登录账号。新任务最多可能需要 1 分钟才会出现。',
  'Last confirmed at {time}': '上次确认：{time}',
  'Account refresh unavailable. Previous account data is kept.': '账号刷新暂不可用，保留上次账号数据。',
  'Account identity is being checked.': '正在确认切换后的账号。',
  'Quota period': '额度周期',
  '{count} tasks with recorded usage': '{count} 个任务有记录消耗',
  'Input': '输入', 'Output': '输出', 'Cached within input': '输入中缓存',
  'Top 3 tasks in this range': '本范围消耗 TOP 3',
  'No positive quota estimates in this range.': '此范围暂无可用的正值额度估算。',
  'Waiting for range data…': '等待范围数据…',
  'Current activity': '当前活动',
  'Live': '实时',
  'Monitor activity now · independent of the date filter': 'Monitor 当前活动 · 不受日期筛选影响',
  'Active tasks': '正在运行的任务',
  'Latest recorded activity': '最近记录活动',
  'Activity connection unavailable; showing the last records.': '实时连接不可用，显示上次记录。',
  'Data coverage': '数据覆盖',
  'Partial data': '部分数据',
  'Included records complete': '已纳入记录齐全',
  'Archive scope limited': '归档范围受限',
  'Details': '详情',
  'Local records only. + marks a partial value; -- means unavailable, not zero.': '仅统计本地记录。+ 表示部分数据；-- 表示不可用，不是零。',
  'Included tasks': '纳入统计的任务',
  'Tasks with unknown consumption': '消耗记录不全的任务',
  'Archive coverage': '归档覆盖',
  'Compare task usage and filter local records.': '比较任务消耗，筛选本地记录。',
  'Daily usage, rankings and estimation methodology.': '每日用量、消耗排行与估算依据。',
  'Top 5 tasks': '任务消耗前 5 名',
  'Cancel': '取消',
  'Select for statistics': '选择此账号统计',
  'The page reconnects when the service is ready.': '服务恢复后，页面会自动重新连接。',
  'Confirm restart': '确认重启',
  'Confirm stop': '确认关闭',
  'Manual calibration: normalized to a confirmed account total. Other accounts remain estimates.': '手动校准：按确认的账号总用量归一化，其他账号仍为估算。',
  'Custom dates': '自定义日期',
  'Start date': '开始日期',
  'End date': '结束日期',
  'Apply dates': '应用日期',
  'Quota usage ({plan} equivalent)': '额度消耗（{plan} 等效）',
  'Selected account': '所选账号',
  'All accounts total': '跨账号累计',
  'Recorded account quota': '账号额度记录', 'Current login': '当前登录', 'Last recorded': '最近记录',
  'Previous account': '上一个账号', 'Next account': '下一个账号', 'View account usage': '查看账号用量',
  'Recorded reset time': '记录中的重置时间',
  'Recorded at {time}. This account is not being refreshed; switching this view does not change your login.': '记录时间：{time}。此账号未实时刷新，切换查看不会改变登录账号。',
  'Accounts appear after Monitor reads their usage while logged in. Task statistics follow the selected account.': '账号登录并被 Monitor 读取用量后会自动保存。任务统计跟随所选账号。',

  'Service': '服务', 'Restart service': '重启服务', 'Stop service': '关闭服务',
  'Update': '更新', 'Updating…': '更新中…', 'Version': '版本', 'Dismiss': '收起提示',
  'Current version': '当前版本', 'Repository version': '仓库版本',
  'Update to v{version}': '更新至 v{version}', 'Update available · Update': '有更新 · 更新',
  'Check failed · Retry': '检查失败 · 重试', 'Check for updates': '检查更新',
  'Previously up to date': '上次已是最新', 'Recheck pending': '待重新检查',
  'Last known repository': '上次仓库版本', 'Check incomplete': '本次检查未完成', 'Check details': '检查详情',
  'Recheck available at {time}': '{time} 后可重新检查', 'Click to check again.': '点击重新检查。',
  'Last attempted at {time}': '本次尝试：{time}',
  'The repository request timed out after 10 seconds.': '仓库请求超过 10 秒，已超时。',
  'The repository hostname could not be resolved.': '无法解析仓库域名。',
  'The repository TLS connection or certificate check failed.': '仓库 TLS 连接或证书验证失败。',
  'The repository connection was refused or interrupted.': '仓库连接被拒绝或中断。',
  'The repository returned an HTTP error.': '仓库返回 HTTP 错误。',
  'GitHub temporarily limited version-check requests.': 'GitHub 暂时限制了版本检查请求。',
  'The repository returned invalid version data.': '仓库返回的版本数据无效。',
  'The check did not complete; no specific cause was recorded.': '检查未完成，未记录到具体原因。',
  'Monitor did not answer the version check within 35 seconds.': 'Monitor 未在 35 秒内返回检查结果。',
  'The browser could not reach the Monitor version endpoint.': '浏览器无法连接 Monitor 的版本检查接口。',
  'Check stage: revision': '阶段：仓库提交。', 'Check stage: manifest': '阶段：版本文件。', 'Check stage: comparison': '阶段：提交比较。',
  'An incomplete version check does not mean installation or updating failed.': '版本检查未完成，不代表安装或更新失败。',
  'Click to check again. Checks are limited to once every 5 minutes.': '点击重新检查更新，最短检查间隔为 5 分钟。',
  'Checking…': '检查中…', 'Last known': '上次结果',
  'Check unavailable': '检查不可用', 'Update available': '有更新', 'Up to date': '已是最新',
  'Checking the repository version…': '正在检查仓库版本…',
  'Includes local unpublished changes.': '包含本机尚未发布的修改。',
  'Repository check unavailable. Showing the last known version.': '仓库检查暂不可用，显示上次确认的版本。',
  'Repository check unavailable. Update status is unknown.': '仓库检查暂不可用，是否有更新尚未确认。',
  'Includes the latest repository changes.': '已包含仓库最新提交。',
  'A newer repository commit is available.': '仓库中有新的提交可更新。',
  'Update status is unknown.': '是否有更新尚未确认。',
  'Update from tabztggg/codex-monitor · main': '更新至 tabztggg/codex-monitor 的 main 分支最新版',
  'Repository updates require a managed Windows installation.': '需通过 Windows 托管安装使用仓库更新。',
  'Update Monitor from the repository?': '从仓库更新 Monitor？',
  'Install the latest main commit from tabztggg/codex-monitor. Your configuration and usage cache are preserved.': '安装 tabztggg/codex-monitor 仓库 main 分支的最新提交，保留现有配置与用量缓存。',
  'Monitor stays available during download and build, then stops briefly to install and restart. The page reconnects automatically. If installation fails, the previous version is restored.': '下载和构建期间仍可使用，准备完成后会短暂关闭服务、安装并重新启动，页面自动重连。安装失败时会恢复之前的版本。',
  'Confirm update': '确认更新',
  'Requesting repository update…': '正在提交更新请求…',
  'Checking the latest repository version…': '正在检查仓库最新版…',
  'Downloading the update. Monitor remains available…': '正在下载更新，Monitor 仍可使用…',
  'Building the update. Monitor remains available…': '正在构建更新，Monitor 仍可使用…',
  'Update prepared. Preparing to restart…': '更新已准备好，即将重启…',
  'Installing the update…': '正在安装更新…',
  'Update installed. Waiting for Monitor to restart…': '更新已安装，等待 Monitor 重新启动…',
  'Monitor updated successfully.': 'Monitor 更新成功。',
  'Monitor is already up to date.': 'Monitor 已是仓库最新版。',
  'Latest repository commit is already installed. Local unpublished changes were kept.': '已包含仓库最新提交，保留本机尚未发布的修改。',
  'The updated service failed its health check. The previous version was restored.': '新版服务健康检查失败，已恢复之前的版本。',
  'The update build is incomplete. The running service was not changed.': '更新构建不完整，当前服务未更改。',
  'Update failed.': '更新失败。',
  'Another service action is in progress.': '已有服务操作正在进行，请等待完成。',
  'Service action failed.': '服务操作失败。',
  'Connection interrupted. Waiting for update status…': '连接暂时中断，正在等待更新结果…',
  'Managed launcher required': '需要使用托管启动器。',
  'Service action already pending': '已有服务操作正在进行。',
  'Windows standalone installation required for updates.': '需要 Windows 独立安装版才能更新。',
  'Could not start the update. Check the installation directory permissions.': '无法启动更新，请检查安装目录权限。',
  'Could not start the update. Another installation may be running, or the installation directory is not writable.': '无法启动更新：其他安装流程可能正在运行，或安装目录不可写。',
  'Update command timed out. Check logs/service-update.log.': '更新命令超时，请查看 logs/service-update.log。',
  'The previous update was interrupted before installation. The installed version is unchanged.': '上次更新在安装前中断，现有版本未更改。',
  'Cannot read the latest main commit from the update repository.': '无法读取更新仓库 main 分支的最新提交。',
  'Updates require npm and PowerShell 7. The running service was not changed.': '更新需要 npm 和 PowerShell 7，当前服务未更改。',
  'Downloaded revision did not match the requested commit.': '下载的版本与指定提交不一致。',
  'The repository did not contain a valid Codex Monitor package.': '仓库中没有有效的 Codex Monitor 安装包。',
  'The selected repository version does not support safe in-app updates. The running version was kept.': '仓库目标版本不支持安全的网页更新，已保留当前运行版本。',
  'Update failed. Check logs/service-update.log.': '更新失败，请查看 logs/service-update.log。',
  'Restart Monitor service?': '确定重启 Monitor 服务？',
  'Stop Monitor? Use the desktop shortcut to start it again.': '确定关闭 Monitor？关闭后可通过桌面快捷方式重新启动。',
  'Monitor stopped. Use the desktop shortcut to start it again.': '已发送关闭指令，请通过桌面快捷方式重新启动。',
  'Restarting Monitor…': '正在重启 Monitor…',
  'Restart not confirmed. Try the desktop shortcut.': '尚未确认重启完成，请尝试桌面快捷方式。',
  'Service action not confirmed. Refresh to check its state.': '尚未确认操作结果，请刷新检查服务状态。',
  'Available with a managed launcher.': '需使用托管启动器运行 Monitor。',
  'Current account / Across accounts': '当前账号 / 跨账号',
  'Official lifetime usage': '官方累计用量',
  'Task lifetime, including subtasks. One full weekly allowance of the query account = 100%. Not this quota period; independent of the plan comparison selector.': '任务累计，包含子任务。以查询账号的一份完整周额度为 100%。不是本周期用量，不受套餐对比选项影响。',
  'Reading official usage…': '正在读取官方用量…',
  'Official usage is not available yet. Local estimates remain available.': '官方用量暂不可用，仍可查看本地估算。',
  'of a full weekly allowance': '占一份完整周额度',
  'Credits used': '已用点数',
  'Breakdown percentages are shares of this task’s official included-plan usage. Credits are separate; zero credits does not mean zero plan usage.': '分布百分比表示该任务官方套餐用量的组成。点数单独计量；点数为 0 不代表没有消耗套餐额度。',
  'Showing the last confirmed official data; background updates may be delayed.': '显示上次确认的官方数据，后台更新可能有延迟。',
  'Query account': '查询账号', 'CLI account': 'CLI 登录账号',
  'Official data can lag behind live usage. Cached for five minutes; read only when a task is expanded.': '官方数据可能滞后于实时用量。缓存 5 分钟，仅在展开任务时读取。',
  'Official data may lag. Refreshes every 10 minutes while expanded and visible; cached for at least five minutes.': '官方数据可能滞后。仅在任务展开且页面可见时每 10 分钟刷新，缓存至少 5 分钟。',
  'Next refresh at {time}': '下次刷新：{time}',
  'Low': '轻度', 'Medium': '中等', 'High': '高', 'Extra high': '极高', 'Maximum': '最高',
  'Minimal': '最低', 'None': '无', 'Standard': '标准', 'Fast': '快速', 'Priority': '优先',
  'Model': '模型', 'Reasoning effort': '推理强度', 'Speed': '速度',
  'Selected account %': '所选账号占比',
  'Selected account %: {account} · This quota period · One {plan} week = 100% · Allocated from recorded quota increases.': '所选账号占比：{account} · 本周期 · 一份 {plan} 周额度 = 100% · 按记录到的额度增量分配。',
  'Selected-account quota is allocated from recorded quota increases using response cost weights. Unsupported amounts remain unattributed. Cross-account usage uses a separate calibration reference. One {plan} week = 100%.': '所选账号占比按记录到的额度增量、依回复费用权重分配；依据不足的部分保留为未归属。跨账号等效消耗使用独立校准基准。一份 {plan} 周额度 = 100%。',
  'Account quota reconciliation': '账号额度对账',
  'Retaining the previous cross-account reference until current-window records support a new calibration.': '沿用历史跨账号基准，待本周期记录足以支持新校准后再更新。',
  'Reference quota reset': '校准参考周期结束',
  'Calibration quota / cost coverage': '校准额度 / 费用覆盖率',
  'Automatic cross-account calibration requires at least 5 quota percentage points and 90% coverage of both quota increases and matching priced costs. Otherwise the previous reference is retained.': '跨账号自动校准要求至少 5 个百分点的额度变化，且额度增量、已匹配费用两项覆盖率均达到 90%；否则保留已有基准。',
  'Account used': '账号已用',
  'Outside task scope': '当前任务范围外',
  'Unattributed quota': '未归属额度',
  'Included tasks + outside task scope + unattributed quota = account used. Search, hidden rows and sorting do not change these totals.': '当前任务 + 范围外任务 + 未归属额度 = 账号已用。搜索、隐藏任务和排序不改变这些合计。',
  'Recorded account quota increases are allocated by response cost weights in the same observation interval. Missing account windows, prices, observation gaps and consumption before the first reading remain unattributed. This is an estimate, not official per-task usage.': '记录到的账号额度增量，按同一观测区间的回复费用权重分配。缺少账号周期、价格或连续观测记录，以及首次观测前的消耗，保留为未归属。这是估算，不是官方单任务用量。',
  'Matching weekly resets (within 60 seconds) estimate account identity; they do not prove it. Account reconciliation uses the account’s own quota, independently of the cross-account calibration reference.': '周重置时间匹配（允许 60 秒误差）用于估算账号归属，不能证明账号身份。账号对账使用该账号自身的额度，与跨账号校准基准分开计算。',
  'The time range controls cross-account summary equivalents, cost, tokens and trends. The right-hand task quota always shows lifetime usage. Selected account % always uses the current quota period.': '时间范围影响跨账号汇总等效消耗、费用、Token 和趋势；任务额度右侧始终显示任务累计；所选账号占比始终统计本周期。',
  'Plan comparison changes both current-account and cross-account equivalents, including project totals. One {plan} weekly allowance = 100%.': '套餐对比同时影响所选账号占比和跨账号等效消耗，包括项目汇总。一份 {plan} 周额度 = 100%。',
  'Today and Last 7 days use calendar days on the monitor computer. Current quota period follows the account reset window. Selected account % stays on that quota period when another time range is selected.': '今天和近 7 天按 Monitor 所在电脑的自然日统计，本周期按账号额度重置时间划定。切换其他时间范围时，所选账号占比仍统计本周期。',
  'Dashboard navigation': '仪表盘导航', 'Usage overview': '用量总览', 'Task details': '任务明细',
  'Trends & methodology': '趋势与依据', 'Current account quota': '当前账号额度',
  '{percent} quota remaining': '额度剩余 {percent}', 'Next reset': '距离下次重置',
  'Remaining quota': '剩余额度', 'Time remaining in this period': '本周期剩余时间',
  'Account snapshots and cross-account estimates, clearly separated.': '账号额度快照与跨账号估算，分开看清。',
  'Cross-account usage estimate': '跨账号用量估算', 'No project': '未分配项目',
  'May exceed 100%': '可超过 100%', 'API-equivalent estimate': 'API 等价估算',
  'Based on local records and observed quota changes.': '基于本地记录与观测到的额度变化估算。',
  'Estimation basis': '估算依据',
  'Current account': '当前账号', 'Across accounts': '跨账号', 'Local records': '本地记录',
  'Time zone: {zone}': '时区：{zone}', 'Starts': '开始', 'Ends / resets': '结束／重置',
  'Statistics start': '统计开始', 'Data through': '数据截至',
  'The current account’s quota window defines this range; equivalent usage combines local records across accounts.': '本范围按当前账号的额度重置周期划定；等效消耗汇总范围内跨账号的本地记录。',
  'This quota period has ended. Waiting for the renewed quota window.': '此额度周期已结束，正在等待新的额度周期。',
  'Showing the last confirmed account snapshot from {time}. Retrying automatically.': '显示 {time} 最后确认的账号数据，正在自动重试。',
  'Last confirmed account': '上次确认的账号',
  'Table view': '表格视图', 'Full table': '完整表格', 'Simple view': '精简视图',
  'Simple view shows one metric. Expand a task for all metrics, or select Full table to choose columns.': '精简视图显示一个指标。展开任务可查看全部指标，或切换完整表格设置显示列。',
  'Scroll horizontally for more columns, or choose Simple view.': '可左右滚动查看其余列，或切换精简视图。',
  'Quota %': '额度占比', 'Est. cost': '估算费用', '{plan} equiv.': '{plan} 等效消耗', 'Tokens': 'Token 数',
  'Account · Period': '账号 · 本周期', 'This period': '本周期', 'Lifetime': '任务累计', '7 days': '近 7 天',
  'Using previous calibration; updating in the background ({count}/5 percentage points).': '沿用历史校准值，后台持续校准（有效样本 {count}/5 个百分点）。',
  'Calibration reference updated': '校准参考值更新时间',
  'CLI account · Details': 'CLI 账号 · 详情',
  'Account details': '账号详情',
  'Time range applies to cost and tokens. Quota columns keep their own periods.': '时间范围影响费用和 Token；额度列分别固定为本周期与任务累计。',
  '{count} included tasks': '已纳入 {count} 个任务',
  'Archives: all {count}': '归档：全部 {count} 个',
  'Archives: latest {count} of {total}': '归档：最近 {count} / 共 {total} 个',
  'Local records · estimates may be incomplete': '本地记录 · 估算可能不完整',
  'Activity today': '今日有活动',
  'Across accounts · Lifetime': '跨账号 · 任务累计',
  'Task data unavailable. Retry refresh.': '任务数据暂不可用，请重试刷新。',
  'Accounts are saved after their usage is read. Selection affects only the task table’s selected-account quota; summaries and trends combine accounts.': '选择账号仅影响任务表的所选账号额度；汇总与趋势合并各账号记录。',
  'Daily trend metric': '日趋势指标',
  'Some records have no date and cannot be assigned to a day. Daily values are partial (+).': '部分记录缺少时间，无法归入具体日期；每日数值为部分数据（+）。',
  'Full bar = {percent} quota. Values keep the weekly allowance denominator.': '满格代表 {percent} 周额度，数值仍以一份周额度为 100%。',
  'Top 5 projects by equivalent quota': '项目等效额度消耗前 5 名',
  'Top 5 tasks by equivalent quota': '任务等效额度消耗前 5 名',
  'Parent task unavailable': '父任务不可用',
  'Rankings show across-account quota consumed in the selected period. One {plan} week = 100%; not a share of total consumption.': '排行统计所选时间范围内的跨账号等效额度消耗。一份 {plan} 周额度 = 100%，不是占总消耗的比例。',
  'Ranking percentages use the selected metric total across all tasks in this period, not only the top 5. Missing records may affect shares.': '消耗占比 = 当前指标下该项目或任务的消耗 ÷ 所选范围全部任务的总消耗，并非仅前 5 名合计。缺失记录可能影响占比。',
  'More actions': '更多操作', 'Shown metric': '显示指标',
  'Scope help': '范围说明', 'Comparison help': '折算说明',
  'Equivalent usage · Cost · Tokens': '影响：等效消耗 · 费用 · Token',
  'Waiting for calibration': '等待校准', 'No priced usage in this range': '此范围暂无可估算用量',
  'Equivalent usage divides the selected-period cost by the calibration reference. Account quota attribution only allocates increases observed since monitoring began; earlier usage in the same task can be unattributed. The two estimates are not interchangeable, even for one account.': '等效消耗用所选范围的费用除以校准基准。账号额度占比仅分配开始观测后的额度增长；同一任务更早的消耗可能尚未归因。因此，即使只使用一个账号，两项估算也不能直接等同。',
  'Includes hidden tasks · + partial data · -- unavailable': '包含隐藏任务 · + 部分数据 · -- 暂不可用',
  'Usage account': '用量所属账号', 'Unknown account': '账号未知', 'API key account': 'API Key 账号',
  'Source: Monitor’s Codex CLI login. This may differ from the account in the Codex desktop app.': '来源：Monitor 使用的 Codex CLI 登录账号，可能与 Codex 桌面应用中的账号不同。',
  'Updated at {time}': '更新时间：{time}',
  'Account changed while reading usage. Waiting for the next refresh.': '读取用量时账号发生变化，等待下次刷新。',
  'Statistics time range': '统计时间范围',
  'Equivalent usage comparison': '等效消耗对比套餐',
  'All accounts': '跨账号',
  '{plan} equivalent usage': '{plan} 等效消耗',
  'One {plan} week = 100%': '一份 {plan} 周额度 = 100%',
  'Applies to equivalent usage, estimated cost, tokens, summaries and trends. Account quota attribution is only available for the current quota period.': '影响等效消耗、估算费用、Token 列，以及汇总和趋势；账号额度占比仅在本周期可用。',
  'Changes only equivalent usage: task and project rows, summary and trend. One {plan} weekly allowance = 100%.': '仅切换任务、项目、汇总和趋势中的等效消耗；一份 {plan} 周额度 = 100%。',
  'Equivalent usage compares all locally recorded accounts with one {plan} weekly allowance in the selected period. Values may exceed 100%.': '等效消耗将所选范围内本机各账号的用量，折算为一份 {plan} 周额度的百分比，可超过 100%。',
  'Nominal comparison: Pro 20x : Pro 5x : Plus = 20 : 5 : 1. The same usage is multiplied by 1, 4 or 20 from the calibrated 20x estimate. This does not change the recorded account tier or represent an official bill.': '按标称倍率估算：Pro 20x : Pro 5x : Plus = 20 : 5 : 1。同一用量在原 20x 校准估算上分别乘以 1、4、20；不会修改记录中的账号套餐，也不代表官方账单。',
  'Current quota period': '本周期', 'Last 7 days': '近 7 天', 'Time range': '统计时间范围',
  'Selected account · This period': '所选账号 · 本周期', 'All accounts · Selected period': '跨账号 · 所选范围',
  'Selected period': '所选时间范围', 'Selected period · USD': '所选范围 · 美元',
  'Estimated cost': '估算费用', 'One 20x week = 100%': '一份 20x 周额度 = 100%',
  'Scope totals': '范围合计', '{count} tasks': '{count} 个任务',
  'Includes hidden tasks in the selected archive scope. Search and row filters only change the list. + means partial data; -- means unavailable.': '包含当前归档范围内被隐藏的任务。搜索和行筛选仅影响列表。+ 表示部分数据，-- 表示不可用。',
  'Daily trend and project ranking': '每日趋势与项目排行', 'Metric': '统计指标', 'Daily usage': '每日用量', 'Top 5 projects': '项目消耗前 5 名',
  'No daily usage records in this period.': '此时间范围内没有每日用量记录。',
  'The trend shows dates with recorded usage in the selected period. Rankings use the full selected scope, including hidden rows.': '趋势显示所选范围内有用量记录的日期。排行汇总整个统计范围，包含被隐藏的行。',
  'Account attribution is available only for the current quota period.': '账号额度分配仅在本周期范围可用。',
  'Refreshing…': '正在刷新…', 'Automatic refresh paused': '自动刷新已暂停', 'Next refresh in {time}': '{time} 后刷新', 'Refresh now': '立即刷新',
  'Rebuild statistics': '重新统计',
  'Re-read logs in the current archive scope. Saved quota attribution is preserved.': '重新读取当前归档范围内的日志，保留已保存的额度分配。',
  'View options': '视图选项', 'Density': '显示密度', 'Comfortable': '舒适', 'Compact': '紧凑', 'Visible columns': '显示列',
  'Loading the selected period. Previous results remain labeled with their original period.': '正在加载所选时间范围，完成前保留原范围的结果和标识。',
  'All available history': '全部可用历史', 'Period unavailable': '周期暂不可用',
  'Statistics help and estimation basis': '统计说明与估算依据',
  '20x equivalents use one Pro 20x weekly allowance as 100%, for usage in the selected period. All locally recorded accounts are included; values may exceed 100%.': '20x 等效消耗以一份 Pro 20x 周额度为 100%，折算所选时间范围内本机各账号的用量，数值可以超过 100%。',
  'Calibration observations': '校准样本', '{count} percentage points': '{count} 个百分点',
  'Manual normalization target': '手动归一化目标',
  'Estimated cost per 1% of 20x': '20x 每 1% 对应估算费用', 'Unpriced tokens': '未定价 Token', 'Tokens without timestamps': '缺少时间戳的 Token',
  'Daily boundary time zone': '每日统计时区', 'Last successful refresh': '上次成功刷新', 'Scrollable task table': '可滚动任务表格',
  'Today and Last 7 days use calendar days on the monitor computer. Current quota period follows the account reset window. Account quota attribution is only available for that period; no historical account totals are fabricated.': '今天和近 7 天按监控电脑的自然日统计，近 7 天包含今天；本周期按账号额度重置时间计算。账号额度分配仅有本周期数据，其他时间范围显示不可用。',
  'Project and scope totals include hidden rows. Click column headings to sort. + means incomplete data; -- means unavailable.': '项目和范围合计包含被隐藏的行。点击列标题可排序。+ 表示数据不完整，-- 表示不可用。',
  'API-equivalent cost for recorded usage in the selected period. This is an estimate, not a ChatGPT subscription charge, and excludes tool-call fees.': '所选时间范围内已记录用量的 API 等价估算费用，并非 ChatGPT 套餐账单，不包含工具调用费用。',
  'Auto-updating': '自动刷新',
  'Task refresh interval': '任务自动刷新间隔',
  '30 seconds': '30 秒',
  '1 minute': '1 分钟',
  '{count} minutes': '{count} 分钟',
  '20x equivalent usage': '20x 等效消耗',
  'All accounts · Weekly estimate': '跨账号 · 本周估算',
  '20x equivalent: one 20x weekly allowance = 100%; all accounts recorded locally are combined, with no 100% cap. Uses the current weekly period and selected archive scope.': '20x 等效消耗：一份 20x 周额度为 100%，合计本机记录中的各账号消耗，不设 100% 上限。采用当前周周期和选定的归档范围。',
  'All recorded Pro accounts are treated as 20x, as confirmed by the owner. The conversion uses observed weekly quota changes and API-equivalent token costs; it is not an official allowance or bill. Missing logs, other devices, tools and unpriced models can affect the estimate.': '根据用户确认，记录中的 Pro 账号均按 20x 处理。使用观测到的周额度变化和 Token 的 API 等价费用校准，不代表官方额度或账单。缺失日志、其他设备、工具和未定价模型可能影响估算。',
  'Period: {start} – {end}.': '统计周期：{start} 至 {end}。',
  'Waiting for enough recorded 20x weekly quota changes; -- means unavailable.': '等待足够的 20x 周额度变化记录完成校准；-- 表示暂不可用。',
  'Estimated 20x weekly equivalents for all local accounts in this project. Includes hidden rows in the selected scope. + means some usage is missing.': '此项目各账号本地记录的 20x 周额度等效估算，包含当前范围内被隐藏的行。+ 表示部分用量缺失。',
  'Estimated local usage across accounts in the current weekly period, divided by the calibrated cost of 1% of a 20x allowance. May exceed 100%. + means unpriced usage is excluded; -- means unavailable.': '当前周周期各账号的本地用量，除以校准得到的 20x 每 1% 额度对应费用。可以超过 100%。+ 表示未计入没有模型价格的用量；-- 表示暂不可用。',
  'Tasks': '任务', 'Task': '任务', 'Status': '状态', 'Activity': '最近活动',
  'Active': '进行中', 'Today': '今天', 'All': '全部', 'Finished': '已结束', 'Archived': '已归档',
  'Search tasks': '搜索任务', 'Search tasks or projects…': '搜索任务或项目…',
  'Filter tasks': '筛选任务', 'Sort tasks': '任务排序', 'Highest usage': '用量从高到低', 'Last activity': '最近活动',
  'Ascending': '升序', 'Descending': '降序', '{column} · {direction}': '{column} · {direction}',
  'Sort {column}: {direction}': '按{column}排序：{direction}',
  'Click a column heading to reverse its sort. Projects use their full totals or latest activity; tasks sort within each project. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题切换升降序。项目按全部任务的汇总值或最近活动排序，任务在各自项目内排序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Hide archived tasks': '隐藏归档任务', 'Show archived tasks': '显示归档任务',
  'Group by project': '按项目分组',
  'Project totals include quota, lifetime cost and lifetime tokens for unarchived tasks and the selected archives. Search and hiding rows do not change totals. + means incomplete data; -- means unavailable. The account quota covers all activity.': '项目汇总未归档任务和选定归档的额度占比、累计费用及总 Token 数，搜索或隐藏行不改变汇总。+ 表示数据不完整，-- 表示不可用。账户总额度覆盖全部活动。',
  'Click a column heading to sort all tasks in the selected scope, then click again to reverse. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题对当前范围内的全部任务排序，再次点击切换升降序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Estimated lifetime API-equivalent cost of tasks in this project within the selected scope. + means a partial estimate; -- means unavailable.': '当前统计范围内此项目全部任务的累计 API 等价估算费用。+ 表示部分估算，-- 表示不可用。',
  'Recorded lifetime tokens in this project: {count}. + means incomplete data.': '此项目记录的累计 Token 总数：{count}。+ 表示数据不完整。',
  'Calculate all archives': '统计所有归档',
  'Only calculate the latest 30 archives': '仅统计最近 30 个归档',
  'Return to the latest 30 archives': '返回最近 30 个归档',
  'Retry all archive statistics': '重试统计所有归档',
  'Calculating all archives…': '正在统计全部归档…',
  'Calculating all archives… Keeping the previous results until complete.': '正在统计全部归档…完成前保留原有结果。',
  'Statistics include all {count} archived tasks.': '当前统计全部 {count} 个归档任务。',
  'Statistics include only the {count} most recently archived tasks.': '当前仅统计最近 {count} 个归档任务。',
  'Only hide archived rows; the selected archive scope still counts toward usage.': '只隐藏归档任务行，当前选定范围内的归档仍计入统计。',
  'Project percentages sum unarchived tasks and the selected archives; search and hiding rows do not change those totals. + means some usage is unknown. The account quota still covers all activity.': '项目占比汇总未归档任务和当前选定的归档；搜索或隐藏行不改变汇总。+ 表示部分用量未知。账户总额度仍覆盖全部活动。',
  'Click a column heading to reverse its sort. Projects use totals in the selected scope or latest activity; tasks sort within each project. Status order: Active, Finished, Archived. Unknown values stay last.': '点击列标题切换升降序。项目按当前统计范围的汇总值或最近活动排序，任务在各自项目内排序。状态顺序：进行中、已结束、已归档；未知值始终置后。',
  'Project total for this period within the selected archive scope, including hidden rows. + means additional usage is unknown.': '当前归档统计范围内的项目本周期额度占比，包含被隐藏的行。+ 表示还有未知用量。',
  'Includes selected archives': '含选定范围的归档',
  'Only hide archived rows; all archives still count toward usage.': '只隐藏列表中的归档任务，用量统计仍包含全部归档任务。',
  'Show more archived tasks ({count} remaining)': '显示更多归档任务（还有 {count} 个）',
  'Displayed / matching tasks': '当前显示 / 匹配任务总数',
  '{shown} shown / {total} total tasks': '{shown} 显示 / {total} 总任务',
  'Last successful refresh: {time}': '上次成功刷新：{time}',
  'Update failed · showing last data': '刷新失败 · 显示上次数据',
  'Auto-updating · every 30 s': '自动刷新 · 每 30 秒', 'Loading task usage…': '正在加载任务用量…',
  'Could not refresh tasks: {error}': '无法刷新任务：{error}', 'Loading tasks…': '正在加载任务…', 'No matching tasks.': '没有匹配的任务。',
  'Consumption before observation and increments without sufficient recorded usage remain unattributed. Filters do not change attribution.': '开始观测前的消耗，以及缺少足够用量记录的增量，保留为未分配额度。筛选不会改变分配结果。',
  'Attribution observed since {time} · Unattributed quota: {percent}': '额度分配观测始于 {time} · 未分配额度：{percent}',
  'Project percentages sum all tasks in this period, regardless of filters; + means some task usage is unknown.': '项目百分比汇总全部任务的本周期额度占用，不受列表筛选影响；+ 表示部分任务用量未知。',
  'Project total for this period, including hidden archives. + means additional usage is unknown.': '该项目全部任务的本周期额度占用之和，包含未显示的归档任务。+ 表示已有统计之外仍有未知用量。',
  'Includes all archives': '含全部归档任务', 'Some usage unknown': '部分用量未知',
  'Unassigned project': '未分配项目', 'Unknown project · {id}': '未识别项目 · {id}',
  'Approx. quota %': '估算额度占比', 'Observed this period': '本周期观测值',
  'Estimated total cost': '估算总费用', 'Task lifetime · USD': '任务累计 · 美元',
  'Total tokens': '总 Token 数', 'Task lifetime': '任务累计', 'Archived at {time}': '归档于 {time}',
  'Open in Codex ↗': '在 Codex 中打开 ↗', 'View live transcript and run': '查看实时记录和运行详情',
  'Task preview': '任务预览', 'No transcript preview available.': '暂无对话预览。',
  'Path': '路径', 'Source': '来源', 'Runs': '运行次数', 'Unavailable': '不可用',
  '{count} total': '总计 {count}', '{count} input': '输入 {count}', '{count} cached': '缓存读取 {count}',
  '{count} cache writes': '缓存写入 {count}', '{count} output': '输出 {count}', '{count} reasoning': '推理 {count}',
  'No API-equivalent cost can be estimated because the recorded model has no matching standard API price. This is not a billed ChatGPT or Codex charge.': '记录中的模型没有匹配的标准 API 价格，无法估算 API 等价费用。这不是 ChatGPT 或 Codex 的实际账单费用。',
  'Lower-bound API-equivalent estimate for recorded usage whose model has a standard API token price. The + indicates that usage from unpriced internal or unknown models is excluded. This is not a billed ChatGPT or Codex charge and excludes tool-call fees.': '这是已知模型价格对应的 API 等价费用下限。+ 表示未计入内部模型或未知模型的用量。这不是 ChatGPT 或 Codex 的实际账单费用，也不包含工具调用费用。',
  'Estimated API-equivalent cost for all recorded token usage in this task, using the recorded model and standard API token prices. It is not a billed ChatGPT or Codex charge and excludes tool-call fees.': '按记录的模型和标准 API Token 价格估算此任务的累计 API 等价费用。这不是 ChatGPT 或 Codex 的实际账单费用，也不包含工具调用费用。',
  'Approximate per-task usage is unavailable because Codex did not expose the current primary quota limit and reset period.': 'Codex 未提供当前主要额度上限和重置周期，暂时无法估算单个任务的额度占比。',
  'Overall Codex': 'Codex 总体', 'API-equivalent cost of priced usage': '已有模型价格的用量对应的 API 等价费用',
  'available local activity': '可用的本地活动记录',
  'Estimated share of {limit} {window} quota attributed to this task during observation. Each quota increase is allocated using {basis}, then accumulated. Earlier allocations are preserved. Pre-observation consumption and increments with missing or unpriced usage remain unattributed. -- means no allocation yet or unavailable data, not zero consumption. This is an estimate, not an official OpenAI per-task measurement. Resets at {time}.': '观测期间分配给此任务的 {limit} {window} 额度估算占比。每次额度增量按{basis}分配后累加，保留之前的分配。开始观测前的消耗，以及缺少用量或价格记录的增量，保留为未分配额度。-- 表示尚未分配或数据不可用，不表示零消耗。这是估算值，不是 OpenAI 官方单任务测量值。重置时间：{time}。',
  'Unknown': '未知', 'Now': '刚刚', '{count} min ago': '{count} 分钟前', '{count} hr ago': '{count} 小时前', '{count} d ago': '{count} 天前',
  'Untitled task · {id}': '未命名任务 · {id}',
  'Overall Codex usage': 'Codex 总体用量', 'remaining': '剩余', 'Quota used': '已用额度', 'Time elapsed': '已过时间',
  'Pace unavailable': '暂无法比较消耗进度', 'Usage is ahead of elapsed time': '额度消耗快于时间进度',
  'Usage is below the proportional pace': '额度消耗慢于时间进度', 'Usage is in line with elapsed time': '额度消耗与时间进度基本一致',
  'Loading overall Codex usage…': '正在加载 Codex 总体用量…', 'Overall Codex quota is unavailable.': 'Codex 总体额度暂不可用。',
  'Waiting for the renewed quota': '等待更新后的额度', '{percent} quota used': '已用额度 {percent}', '{percent} of period elapsed': '本周期已过 {percent}',
  'Codex has not reported the new period yet.': 'Codex 尚未报告新周期的数据。', 'The period or usage data is incomplete.': '周期或用量数据不完整。',
  'Consumption follows the proportional pace of the period.': '额度消耗与本周期的时间进度基本一致。',
  '{count} percentage points above the proportional pace.': '额度消耗比时间进度高 {count} 个百分点。',
  '{count} percentage points below the proportional pace.': '额度消耗比时间进度低 {count} 个百分点。',
  'Reset time unavailable': '重置时间不可用', 'Resets in {duration}': '{duration} 后重置',
  '{days}d {hours}h': '{days} 天 {hours} 小时', '{hours}h {minutes}m': '{hours} 小时 {minutes} 分钟', '{minutes}m': '{minutes} 分钟',
  'Auto shutdown': '自动关机', 'Dry-run': '模拟运行', 'On': '开启', 'Off': '关闭', 'Power': '电源', 'Idle shutdown': '空闲后关机',
  'Enable': '启用', 'Disable': '停用', 'Shutdown in {duration}': '{duration} 后关机',
  'Codex app-server initialized': 'Codex 服务已初始化', 'Waiting for Codex app-server': '正在等待 Codex 服务',
  'Connected': '已连接', 'Connection: {status}': '连接状态：{status}',
  'API-equivalent cost, not a plan charge · Codex Spark excluded': 'API 等价估算费用，并非套餐账单 · 不含 Codex Spark',
  'Off. Enable it to shut down after Codex work finishes.': '已关闭。启用后将在 Codex 任务结束后关机。',
  'Dry-run mode is on. Countdown will not shut down this computer.': '模拟运行模式已开启，倒计时不会让这台电脑真正关机。',
  'Windows shutdown is scheduled. New Codex activity will cancel it.': '已安排 Windows 关机。新的 Codex 活动会取消关机。',
  'No active sessions. Scheduling Windows shutdown after {seconds}s idle.': '没有进行中的任务。空闲 {seconds} 秒后安排 Windows 关机。',
  'Waiting for {count} active Codex sessions to finish.': '正在等待 {count} 个进行中的 Codex 任务结束。',
  'Waiting for one active Codex session to finish.': '正在等待 1 个进行中的 Codex 任务结束。',
  'Armed. Shutdown starts after {idle}s idle, then Windows waits {delay}s.': '已就绪。空闲 {idle} 秒后启动关机计时，Windows 再等待 {delay} 秒。',
  'Shutdown {status}': '关机：{status}', 'No shutdown scheduled': '未安排关机', 'Windows timer {duration}': 'Windows 关机倒计时 {duration}', 'Schedules in {duration}': '{duration} 后安排关机',
  'Run detail': '运行详情', 'Waiting for this run to appear.': '正在等待此运行的数据。',
  'If you opened a stale URL, go back to the dashboard.': '如果打开的是已失效的链接，请返回仪表盘。', 'Back to dashboard': '返回仪表盘',
  'waiting on you': '等待你处理', 'autonomous': '自主执行', 'automation {status}': '自动化：{status}',
  'Tracked threads': '跟踪的任务数', 'Root thread': '根任务', 'Shutdown': '关机', 'not scheduled': '未安排',
  'Arm shutdown rule': '启用关机规则', 'Cancel shutdown': '取消关机',
  'Thread tree': '任务树', 'Root plus spawned agents': '根任务与派生智能体', 'Waiting for thread data…': '正在等待任务数据…',
  'No recent preview yet.': '暂无最近活动预览。', 'Transcript': '对话记录', 'Select a thread': '选择任务',
  'Pick a thread to inspect its stream.': '选择一个任务以查看实时记录。', 'Tool: {name}': '工具：{name}',
  'Inspector': '检查面板', 'No thread selected': '未选择任务', 'Thread metadata appears here.': '任务信息将显示在这里。',
  'Latest turn': '最近一轮', 'no turn yet': '暂无轮次', 'No recent activity summary.': '暂无最近活动摘要。',
  'Plan': '计划', 'No plan updates captured for this turn.': '本轮尚未记录到计划更新。',
  'Diff': '变更差异', 'No diff emitted yet.': '暂无变更差异。', 'Commands': '命令', 'No command output in this turn yet.': '本轮暂无命令输出。',
  'Pending requests': '待处理请求', 'No pending human requests for this thread.': '此任务没有等待人工处理的请求。', 'Shutdown timer': '关机计时器',
  'Waiting on command approval': '等待命令审批', 'Waiting on file-change approval': '等待文件修改审批',
  'Waiting on extra permissions': '等待额外权限', 'Waiting on user input': '等待用户输入', 'Waiting on MCP elicitation': '等待 MCP 信息补充', 'Waiting on external request': '等待外部请求',
  'Command approval': '命令审批', 'File-change approval': '文件修改审批', 'Extra permissions': '额外权限', 'User input': '用户输入', 'MCP elicitation': 'MCP 信息补充', 'External request': '外部请求',
  'Technical details': '技术详情', 'Unable to load data.': '无法加载数据。', 'Action failed.': '操作失败。',
  'Failed to fetch': '网络请求失败', 'NetworkError when attempting to fetch resource.': '网络请求失败',
  'History pagination did not advance.': '任务列表分页没有前进，请稍后刷新。', 'Forbidden origin': '此访问来源未获允许',
  'Codex did not return rate limit data.': 'Codex 未返回额度限制数据。', 'Codex sent malformed rate limit data.': 'Codex 返回的额度数据格式无效。',
  'Request failed with {status}': '请求失败，状态码 {status}',
  'Monitor snapshot request timed out.': 'Monitor 数据请求超时。',
  'Monitor WebSocket connection timed out.': 'Monitor 实时连接超时。',
  'Codex app-server restart is delayed; retry in {seconds} seconds.': 'Codex 后台连接正在等待重试，{seconds} 秒后可重试。',
  'Codex app-server client has been shut down.': 'Codex 后台连接已停止。',
  'Codex app-server closed during initialization.': 'Codex 后台进程在初始化期间退出。',
  'Weekly': '每周', '5-hour': '5 小时', 'Daily': '每日', '{minutes}-minute': '{minutes} 分钟', '{hours}-hour': '{hours} 小时', '{days}-day': '{days} 天',
  'Running': '运行中', 'Idle': '空闲', 'Error': '错误', 'Waiting for you': '等待处理', 'Not loaded': '未加载',
  'Settled': '已结束', 'Disabled': '已停用', 'Armed': '已就绪', 'Debouncing': '等待空闲稳定', 'Scheduled': '已安排',
  'Completed': '已完成', 'Failed': '失败', 'Interrupted': '已中断', 'In progress': '进行中', 'Pending': '待处理',
  'Connecting': '连接中', 'Retrying': '重试中', 'Reconnecting': '重新连接中',
  'CLI': '命令行', 'VS Code': 'VS Code', 'Execution': '执行', 'App server': '应用服务', 'Subagent': '子智能体',
  'Review subagent': '审查子智能体', 'Compaction subagent': '压缩子智能体', 'Spawned subagent': '派生子智能体', 'Other subagent': '其他子智能体',
  'User message': '用户消息', 'Assistant message': '助手消息', 'Reasoning': '推理', 'Command': '命令', 'File change': '文件修改', 'Web search': '网页搜索', 'Image': '图片', 'Tool call': '工具调用',
  'Agent message': '智能体消息', 'Command execution': '命令执行', 'Agent collaboration': '智能体协作', 'MCP tool call': 'MCP 工具调用',
  'Window': '周期', 'Context compaction': '上下文压缩', 'Image generation': '图片生成', 'Entered review mode': '进入审查模式', 'Exited review mode': '退出审查模式',
  'Codex app-server is not running.': 'Codex 服务未运行。',
};

export function translate(language: Language, message: string, params: Params = {}): string {
  const template = language === 'zh' && Object.hasOwn(chinese, message) ? chinese[message] : message;
  return template.replace(/\{(\w+)\}/g, (token, key: string) => Object.hasOwn(params, key) ? String(params[key]) : token);
}

const labels: Record<string, string> = {
  running: 'Running', idle: 'Idle', error: 'Error', waiting_on_human: 'Waiting for you', not_loaded: 'Not loaded',
  settled: 'Settled', disabled: 'Disabled', armed: 'Armed', debouncing: 'Debouncing', scheduled: 'Scheduled', 'dry-run': 'Dry-run',
  completed: 'Completed', failed: 'Failed', interrupted: 'Interrupted', inProgress: 'In progress', pending: 'Pending',
  live: 'Connected', connecting: 'Connecting', retrying: 'Retrying', reconnecting: 'Reconnecting',
  cli: 'CLI', vscode: 'VS Code', exec: 'Execution', appServer: 'App server', unknown: 'Unknown', subAgent: 'Subagent',
  subAgentReview: 'Review subagent', subAgentCompact: 'Compaction subagent', subAgentThreadSpawn: 'Spawned subagent', subAgentOther: 'Other subagent',
  commandApproval: 'Command approval', fileChangeApproval: 'File-change approval', permissionsApproval: 'Extra permissions',
  toolUserInput: 'User input', mcpElicitation: 'MCP elicitation', dynamicToolCall: 'Tool call', authRefresh: 'External request',
  reasoning: 'Reasoning', plan: 'Plan', imageView: 'Image', contextCompaction: 'Context compaction',
  imageGeneration: 'Image generation', enteredReviewMode: 'Entered review mode', exitedReviewMode: 'Exited review mode'
};

export function createI18n(language: Language) {
  const locale = language === 'zh' ? 'zh-CN' : 'en-US';
  const t: Translate = (message, params) => translate(language, message, params);
  return {
    language, locale, t,
    label: (value: string) => t(Object.hasOwn(labels, value) ? labels[value] : value),
    dateTime: (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString(locale) : t('Unavailable'),
    time: (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleTimeString(locale) : t('Unavailable'),
    windowLabel: (value: string) => {
      if (Object.hasOwn(chinese, value)) return t(value);
      const match = value.match(/^(\d+)-(minute|hour|day)$/i);
      return match ? t(`{${match[2].toLowerCase()}s}-${match[2].toLowerCase()}`, { [`${match[2].toLowerCase()}s`]: match[1] }) : value;
    },
    error: (value: string) => {
      const status = value.match(/^Request failed with (\d+)$/);
      const cooldown = value.match(/^Codex app-server restart is delayed; retry in (\d+) seconds\.$/);
      if (cooldown) return t('Codex app-server restart is delayed; retry in {seconds} seconds.', { seconds: cooldown[1] });
      return status ? t('Request failed with {status}', { status: status[1] }) : t(value);
    }
  };
}
export type I18n = ReturnType<typeof createI18n>;
export const LANGUAGE_STORAGE_KEY = 'codex-monitor-language';
export function initialLanguage(storage?: Pick<Storage, 'getItem'>): Language {
  try { return storage?.getItem(LANGUAGE_STORAGE_KEY) === 'zh' ? 'zh' : 'en'; }
  catch { return 'en'; }
}
